--------------------------------------------------------
--  Fichier créé - mardi-novembre-20-2018   
--------------------------------------------------------
REM INSERTING into NHINCELIN.CLIENTS
SET DEFINE OFF;
Insert into NHINCELIN.CLIENTS (NCLI,NOM_CLI,PRENOM_CLI,ADR_RUE,ADR_VILL,PROF,SEXE,DATENAISS,CODEPOSTAL) values ('A0035  ','Arne','Luc','5 Rue des libellules','BIZANOS','Informaticien','m',to_date('11/04/82','DD/MM/RR'),'64320');
Insert into NHINCELIN.CLIENTS (NCLI,NOM_CLI,PRENOM_CLI,ADR_RUE,ADR_VILL,PROF,SEXE,DATENAISS,CODEPOSTAL) values ('A7341  ','Audos','Djamel','22 Rue Masseur','BILLERE','Avocat','m',to_date('20/05/62','DD/MM/RR'),'64140');
Insert into NHINCELIN.CLIENTS (NCLI,NOM_CLI,PRENOM_CLI,ADR_RUE,ADR_VILL,PROF,SEXE,DATENAISS,CODEPOSTAL) values ('A43967X','Aimar','Jean','8 Rue Des primes','PAU','Enseignant','m',to_date('11/02/77','DD/MM/RR'),'64000');
Insert into NHINCELIN.CLIENTS (NCLI,NOM_CLI,PRENOM_CLI,ADR_RUE,ADR_VILL,PROF,SEXE,DATENAISS,CODEPOSTAL) values ('B70524R','Hisson','Paul','45 Avenue des Farces','ARTIX','Medecin gene','m',to_date('07/10/63','DD/MM/RR'),'64170');
Insert into NHINCELIN.CLIENTS (NCLI,NOM_CLI,PRENOM_CLI,ADR_RUE,ADR_VILL,PROF,SEXE,DATENAISS,CODEPOSTAL) values ('D00878C','Move','Guy','11 Rue Friandises','BILLERE','Peintre Bat.','m',to_date('11/04/70','DD/MM/RR'),'64140');
Insert into NHINCELIN.CLIENTS (NCLI,NOM_CLI,PRENOM_CLI,ADR_RUE,ADR_VILL,PROF,SEXE,DATENAISS,CODEPOSTAL) values ('e0442  ','Mansoif','Gerard','51 Rue de la source','PAU','Viticulteur','m',to_date('12/01/75','DD/MM/RR'),'64000');
Insert into NHINCELIN.CLIENTS (NCLI,NOM_CLI,PRENOM_CLI,ADR_RUE,ADR_VILL,PROF,SEXE,DATENAISS,CODEPOSTAL) values ('f0431  ','Darmerie','Jean','22 Rue Poulet','LONS','Militaire','m',to_date('10/06/70','DD/MM/RR'),'64140');
Insert into NHINCELIN.CLIENTS (NCLI,NOM_CLI,PRENOM_CLI,ADR_RUE,ADR_VILL,PROF,SEXE,DATENAISS,CODEPOSTAL) values ('F11581H','Bonblanc','Jean','Route de Bayonne','GAN','Charcutier','m',to_date('22/09/77','DD/MM/RR'),'64290');
Insert into NHINCELIN.CLIENTS (NCLI,NOM_CLI,PRENOM_CLI,ADR_RUE,ADR_VILL,PROF,SEXE,DATENAISS,CODEPOSTAL) values ('F51125R','Proviste','Alain','15 Avenue Surprise','BIZANOS','Gendarme','m',to_date('02/02/59','DD/MM/RR'),'64320');
Insert into NHINCELIN.CLIENTS (NCLI,NOM_CLI,PRENOM_CLI,ADR_RUE,ADR_VILL,PROF,SEXE,DATENAISS,CODEPOSTAL) values ('F8731  ','Minatoire','Elie','26 rue des perdants','GAN','Plombier','m',to_date('10/08/62','DD/MM/RR'),'64290');
Insert into NHINCELIN.CLIENTS (NCLI,NOM_CLI,PRENOM_CLI,ADR_RUE,ADR_VILL,PROF,SEXE,DATENAISS,CODEPOSTAL) values ('G0086  ','Nieuman','Eloi','16 Av des expatries','IDRON','Agent voyage','m',to_date('21/11/80','DD/MM/RR'),'64320');
Insert into NHINCELIN.CLIENTS (NCLI,NOM_CLI,PRENOM_CLI,ADR_RUE,ADR_VILL,PROF,SEXE,DATENAISS,CODEPOSTAL) values ('G0342  ','Lochon','Paul','25 rue des batailles','LONS','Matelassier','m',to_date('26/04/60','DD/MM/RR'),'64140');
Insert into NHINCELIN.CLIENTS (NCLI,NOM_CLI,PRENOM_CLI,ADR_RUE,ADR_VILL,PROF,SEXE,DATENAISS,CODEPOSTAL) values ('g6643  ','Lize','Eva','1 rue des voyageurs','PAU','Commercant','f',to_date('30/12/65','DD/MM/RR'),'64000');
Insert into NHINCELIN.CLIENTS (NCLI,NOM_CLI,PRENOM_CLI,ADR_RUE,ADR_VILL,PROF,SEXE,DATENAISS,CODEPOSTAL) values ('G6811  ','Eulepas','Marc','rue des marcheurs','JURANCON','Artisan macon','m',to_date('17/03/67','DD/MM/RR'),'64110');
Insert into NHINCELIN.CLIENTS (NCLI,NOM_CLI,PRENOM_CLI,ADR_RUE,ADR_VILL,PROF,SEXE,DATENAISS,CODEPOSTAL) values ('H5003  ','Aucarrez','Pierre','314 rue des maths','LESCAR','Enseignant','m',to_date('31/05/61','DD/MM/RR'),'64230');
Insert into NHINCELIN.CLIENTS (NCLI,NOM_CLI,PRENOM_CLI,ADR_RUE,ADR_VILL,PROF,SEXE,DATENAISS,CODEPOSTAL) values ('h9612  ','Atan','Charles','rue de la patience','UZEIN','Medecin gen.','m',to_date('14/06/73','DD/MM/RR'),'64230');
Insert into NHINCELIN.CLIENTS (NCLI,NOM_CLI,PRENOM_CLI,ADR_RUE,ADR_VILL,PROF,SEXE,DATENAISS,CODEPOSTAL) values ('j0672  ','Surpier','Remy','5 rue des guerisons','PAU','Kinesither.','m',to_date('27/08/76','DD/MM/RR'),'64000');
Insert into NHINCELIN.CLIENTS (NCLI,NOM_CLI,PRENOM_CLI,ADR_RUE,ADR_VILL,PROF,SEXE,DATENAISS,CODEPOSTAL) values ('M8349  ','Passe-Edemeyeur','Jean','4 imp. des blagueurs','BILLERE','Journaliste','m',to_date('11/05/79','DD/MM/RR'),'64140');
Insert into NHINCELIN.CLIENTS (NCLI,NOM_CLI,PRENOM_CLI,ADR_RUE,ADR_VILL,PROF,SEXE,DATENAISS,CODEPOSTAL) values ('m8621  ','Tournaile','Marie','38 rue chansonnette','BILLERE','Danseuse','f',to_date('12/03/83','DD/MM/RR'),'64140');
Insert into NHINCELIN.CLIENTS (NCLI,NOM_CLI,PRENOM_CLI,ADR_RUE,ADR_VILL,PROF,SEXE,DATENAISS,CODEPOSTAL) values ('m9652  ','Manvussa','Gerard','5 rue des etonnes','PAU','Voyant','m',to_date('18/08/68','DD/MM/RR'),'64000');
Insert into NHINCELIN.CLIENTS (NCLI,NOM_CLI,PRENOM_CLI,ADR_RUE,ADR_VILL,PROF,SEXE,DATENAISS,CODEPOSTAL) values ('n7601  ','Naitraubu','Jean','20 rue alcool','PAU','Employe bureau','m',to_date('18/08/68','DD/MM/RR'),'64000');
Insert into NHINCELIN.CLIENTS (NCLI,NOM_CLI,PRENOM_CLI,ADR_RUE,ADR_VILL,PROF,SEXE,DATENAISS,CODEPOSTAL) values ('p3428  ','Pourmontailecol','Saturnin','11 rue de l aubisque','PAU','Cycliste','m',to_date('03/11/72','DD/MM/RR'),'64000');
Insert into NHINCELIN.CLIENTS (NCLI,NOM_CLI,PRENOM_CLI,ADR_RUE,ADR_VILL,PROF,SEXE,DATENAISS,CODEPOSTAL) values ('p8432  ','Patriai','Alex','2 rue des baroudeurs','JURANCON','Agent de voyage','m',to_date('09/10/75','DD/MM/RR'),'64110');
Insert into NHINCELIN.CLIENTS (NCLI,NOM_CLI,PRENOM_CLI,ADR_RUE,ADR_VILL,PROF,SEXE,DATENAISS,CODEPOSTAL) values ('Q7721  ','Assain','Marc','33 rue des sangliers','MORLAAS','Veterinaire','m',to_date('14/07/71','DD/MM/RR'),'64160');
Insert into NHINCELIN.CLIENTS (NCLI,NOM_CLI,PRENOM_CLI,ADR_RUE,ADR_VILL,PROF,SEXE,DATENAISS,CODEPOSTAL) values ('R0541  ','Rhabou','Emma','13 rue des saints','PAU','Secretaire','f',to_date('22/11/60','DD/MM/RR'),'64000');
Insert into NHINCELIN.CLIENTS (NCLI,NOM_CLI,PRENOM_CLI,ADR_RUE,ADR_VILL,PROF,SEXE,DATENAISS,CODEPOSTAL) values ('R7325  ','Boquet','Bill','56 rue des jouets','BIZANOS','Coiffeur','m',to_date('17/05/58','DD/MM/RR'),'64320');
Insert into NHINCELIN.CLIENTS (NCLI,NOM_CLI,PRENOM_CLI,ADR_RUE,ADR_VILL,PROF,SEXE,DATENAISS,CODEPOSTAL) values ('R8753  ','Milanedans-Lepre','Vincent','14 rue champetre','BILLERE','Agriculteur','m',to_date('02/12/80','DD/MM/RR'),'64140');
Insert into NHINCELIN.CLIENTS (NCLI,NOM_CLI,PRENOM_CLI,ADR_RUE,ADR_VILL,PROF,SEXE,DATENAISS,CODEPOSTAL) values ('S5871  ','Durepaux','Yves','11 imp des endormis','LONS','Agent postes','m',to_date('25/12/62','DD/MM/RR'),'64140');
Insert into NHINCELIN.CLIENTS (NCLI,NOM_CLI,PRENOM_CLI,ADR_RUE,ADR_VILL,PROF,SEXE,DATENAISS,CODEPOSTAL) values ('T0076  ','Aivudotre','Jean','3 Rue des blases','BORDES','Journaliste','m',to_date('23/06/64','DD/MM/RR'),'64320');
Insert into NHINCELIN.CLIENTS (NCLI,NOM_CLI,PRENOM_CLI,ADR_RUE,ADR_VILL,PROF,SEXE,DATENAISS,CODEPOSTAL) values (' T0663 ','Therieur','Alex','9 rue belle etoile','JURANCON','Agent de voyage','m',to_date('23/04/70','DD/MM/RR'),'64110');
Insert into NHINCELIN.CLIENTS (NCLI,NOM_CLI,PRENOM_CLI,ADR_RUE,ADR_VILL,PROF,SEXE,DATENAISS,CODEPOSTAL) values ('T0964  ','Soucian','Alain',' 27 rue des soucis','PAU','Jardinier','m',to_date('09/07/71','DD/MM/RR'),'64000');
Insert into NHINCELIN.CLIENTS (NCLI,NOM_CLI,PRENOM_CLI,ADR_RUE,ADR_VILL,PROF,SEXE,DATENAISS,CODEPOSTAL) values ('T1574  ','Therieur','Alain','8 rue de la justice','LESCAR','Magistrat','m',to_date('08/02/75','DD/MM/RR'),'64230');
Insert into NHINCELIN.CLIENTS (NCLI,NOM_CLI,PRENOM_CLI,ADR_RUE,ADR_VILL,PROF,SEXE,DATENAISS,CODEPOSTAL) values ('T213547','Piedeudan','Emile','7 rue de la chance','PAU','Employe  bureau','m',to_date('26/08/85','DD/MM/RR'),'64000');
Insert into NHINCELIN.CLIENTS (NCLI,NOM_CLI,PRENOM_CLI,ADR_RUE,ADR_VILL,PROF,SEXE,DATENAISS,CODEPOSTAL) values ('t5641  ','Fontaine','Claire','15 rue de la source','NAY','Employee eaux','f',to_date('06/09/68','DD/MM/RR'),'64800');
Insert into NHINCELIN.CLIENTS (NCLI,NOM_CLI,PRENOM_CLI,ADR_RUE,ADR_VILL,PROF,SEXE,DATENAISS,CODEPOSTAL) values ('U7342  ','Aipasdi','Julie','5 rue des secrets','PAU','Agent secret','f',to_date('10/10/75','DD/MM/RR'),'64000');
Insert into NHINCELIN.CLIENTS (NCLI,NOM_CLI,PRENOM_CLI,ADR_RUE,ADR_VILL,PROF,SEXE,DATENAISS,CODEPOSTAL) values ('v7652  ','Thimaitre','Vincent','8 rue de la mesure','IDRON','Geometre','m',to_date('17/08/61','DD/MM/RR'),'64320');
Insert into NHINCELIN.CLIENTS (NCLI,NOM_CLI,PRENOM_CLI,ADR_RUE,ADR_VILL,PROF,SEXE,DATENAISS,CODEPOSTAL) values ('f04358j','Versere','Annie','3 rue des joyeux','GAN','Secretaire','f',to_date('13/04/70','DD/MM/RR'),'64290');
Insert into NHINCELIN.CLIENTS (NCLI,NOM_CLI,PRENOM_CLI,ADR_RUE,ADR_VILL,PROF,SEXE,DATENAISS,CODEPOSTAL) values ('Z0872  ','Mateur','Annie','1 imp de la tele','PAU','Journaliste','f',to_date('02/08/70','DD/MM/RR'),'64000');
Insert into NHINCELIN.CLIENTS (NCLI,NOM_CLI,PRENOM_CLI,ADR_RUE,ADR_VILL,PROF,SEXE,DATENAISS,CODEPOSTAL) values ('Y083452','Tarebasse','Guy','6 rue des musiciens','PAU','Musicien','m',to_date('11/09/78','DD/MM/RR'),'64000');
Insert into NHINCELIN.CLIENTS (NCLI,NOM_CLI,PRENOM_CLI,ADR_RUE,ADR_VILL,PROF,SEXE,DATENAISS,CODEPOSTAL) values (' r3568 ','Manbu','Gerard','18 rue de Vittel','PAU','Sourcier','m',to_date('15/02/90','DD/MM/RR'),'64000');
Insert into NHINCELIN.CLIENTS (NCLI,NOM_CLI,PRENOM_CLI,ADR_RUE,ADR_VILL,PROF,SEXE,DATENAISS,CODEPOSTAL) values ('Y4522  ','Pasbienfaur','Yvon','4 rue des souffrants','LESCAR','Medecin gene','m',to_date('12/12/76','DD/MM/RR'),'64230');
Insert into NHINCELIN.CLIENTS (NCLI,NOM_CLI,PRENOM_CLI,ADR_RUE,ADR_VILL,PROF,SEXE,DATENAISS,CODEPOSTAL) values ('F4305  ','Edesovetage','Gilles','13 Rue des secours','BIZANOS','Maitre Nageur','m',to_date('15/06/88','DD/MM/RR'),'64320');
Insert into NHINCELIN.CLIENTS (NCLI,NOM_CLI,PRENOM_CLI,ADR_RUE,ADR_VILL,PROF,SEXE,DATENAISS,CODEPOSTAL) values ('G67832E','Edesovetage','Gilles','13 rue des secours','BIZANOS','Maitre Nageur','m',to_date('15/06/88','DD/MM/RR'),'64320');
Insert into NHINCELIN.CLIENTS (NCLI,NOM_CLI,PRENOM_CLI,ADR_RUE,ADR_VILL,PROF,SEXE,DATENAISS,CODEPOSTAL) values ('F68107S','Hebussavabien','Aude','15 Rue des débutants','PAU','Chanteuse','f',to_date('25/06/97','DD/MM/RR'),'64000');
